kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world

---
kind: pipeline
type: docker
name: custom

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
trigger:
  event:
  - custom
