apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: "2020-06-28T21:23:34Z"
  name: prod.lexioapp.com
spec:
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "autoscaling:DescribeAutoScalingGroups",
            "autoscaling:DescribeAutoScalingInstances",
            "autoscaling:DescribeTags",
            "autoscaling:DescribeLaunchConfigurations",
            "autoscaling:SetDesiredCapacity",
            "autoscaling:TerminateInstanceInAutoScalingGroup"
          ],
          "Resource": "*"
        }
      ]
  api:
    loadBalancer:
      type: Internal
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://kops-state.lexioapp.com/prod.lexioapp.com
  dnsZone: prod.lexioapp.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: main
    version: 3.2.24
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-us-east-1a
      name: a
    - instanceGroup: master-us-east-1b
      name: b
    - instanceGroup: master-us-east-1c
      name: c
    memoryRequest: 100Mi
    name: events
    version: 3.2.24
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.16.10
  masterPublicName: api.prod.lexioapp.com
  networkCIDR: 10.23.0.0/16
  networkID: vpc-0034c8dcb11330732
  networking:
    calico:
      majorVersion: v3
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 10.23.1.0/24
    id: subnet-04fa50be47a7adeba
    name: us-east-1a
    type: Private
    zone: us-east-1a
  - cidr: 10.23.2.0/24
    id: subnet-01e81f24c49c7fca4
    name: us-east-1b
    type: Private
    zone: us-east-1b
  - cidr: 10.23.3.0/24
    id: subnet-09394461b568b9abf
    name: us-east-1c
    type: Private
    zone: us-east-1c
  topology:
    dns:
      type: Private
    masters: private
    nodes: private
